friend= dict(name="Yahya",age="12",city="Colombo")
print ("Keys:",friend.keys())
print ("Values:",friend.values())
print("Items:",friend.items())
friend.pop("age")
print ("pop:",friend)
friend.update({"age":"15"})
print ("Update:",friend)
print("With Get:",friend.get("name"))
print("Without Get:",friend["name"])
friend.popitem()
print("popitem:",friend)
friend.clear()
print ("clear:",friend)

